apiVersion: apps/v1
kind: Deployment

metadata:
  name: primeiroprojeto

spec:
  replicas: 2

  selector:
    matchLabels:
      app: primeiroprojeto

  template:
    metadata:
      labels:
        app: primeiroprojeto

    spec:
      containers:
        - name: primeiroprojeto

          image: primeiroprojeto:v1

          imagePullPolicy: Never

          ports:
            - containerPort: 8080